{% set name = "amazon-braket-default-simulator" %}
{% set version = "1.24.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a2e8b64e8af26a495eef6ef157f7c3253d6cb789f9f220fc3ed23936243ac5bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - sympy
    - pydantic >2
    - amazon-braket-schemas >=1.21.2
    - antlr4-python3-runtime ==4.9.2
    - numpy
    - opt-einsum
    - python >=3.8
    - scipy

test:
  imports:
    - braket
    - braket.default_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-default-simulator-python
  summary: An open source quantum circuit simulator to be run locally with the Amazon Braket SDK
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
