{% set name = "amazon-braket-default-simulator" %}
{% set version = "1.23.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 70788f846c8541a86c228d50a1ea9f48b337ca048c727916b5abd4930bc2648c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - sympy
    - pydantic >2
    - amazon-braket-schemas >=1.21.2
    - antlr4-python3-runtime ==4.9.2
    - numpy
    - opt-einsum
    - python >=3.8
    - scipy

test:
  imports:
    - braket
    - braket.default_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-default-simulator-python
  summary: An open source quantum circuit simulator to be run locally with the Amazon Braket SDK
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
