{% set name = "amazon-braket-default-simulator" %}
{% set version = "1.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-default-simulator-{{ version }}.tar.gz
  sha256: 9914cd3752654a077bca59d17238b8e7e2ba9d4ee34d929fe0a07b8eb9c04d30

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic ==1.9.0
    - amazon-braket-schemas >=1.12.0
    - antlr4-python3-runtime ==4.9.2
    - numpy
    - opt-einsum
    - python >=3.7
    - scipy

test:
  imports:
    - braket
    - braket.default_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-default-simulator-python
  summary: An open source quantum circuit simulator to be run locally with the Amazon Braket SDK
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
