{% set name = "amazon-braket-default-simulator" %}
{% set version = "1.38.1" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 17b62229a768c92e503b2d9e14d29bdea846a68cc74fcf5bf262d1a380ecb00b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - setuptools ==81.0.0
    - numba
    - opt_einsum
    - sympy
    - pydantic >2
    - amazon-braket-schemas >=1.26.1
    - antlr4-python3-runtime ==4.13.2
    - numpy
    - opt-einsum
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - braket
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-default-simulator-python
  summary: An open source quantum circuit simulator to be run locally with the Amazon Braket SDK
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
