{% set name = "amazon-braket-default-simulator" %}
{% set version = "1.30.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 99cc611c86a14839f36dd102fa3f6efad2884d77a1db76d30ef778908ec11b52

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - opt_einsum
    - sympy
    - pydantic >2
    - amazon-braket-schemas >=1.25.0
    - antlr4-python3-runtime ==4.13.2
    - numpy
    - opt-einsum
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - braket
    - braket.default_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-default-simulator-python
  summary: An open source quantum circuit simulator to be run locally with the Amazon Braket SDK
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
