{% set name = "amazon-braket-default-simulator" %}
{% set version = "1.20.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amazon-braket-default-simulator-{{ version }}.tar.gz
  sha256: 7bd93071b140ddbfd290ab97d4f213c9240872049ad46d8fe5d7522a9ad03bb7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - sympy
    - pydantic
    - amazon-braket-schemas >=1.18.0
    - antlr4-python3-runtime ==4.9.2
    - numpy
    - opt-einsum
    - python >=3.8
    - scipy

test:
  imports:
    - braket
    - braket.default_simulator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/amazon-braket-default-simulator-python
  summary: An open source quantum circuit simulator to be run locally with the Amazon Braket SDK
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - BastianZim
